version: '3.6'
services:
    influxdb:
      image: influxdb:2.0
      container_name: influxdb_css
      restart: always
      environment:
        - DOCKER_INFLUXDB_INIT_MODE=setup 
        - DOCKER_INFLUXDB_INIT_USERNAME=cisco
        - DOCKER_INFLUXDB_INIT_PASSWORD=cisco,cisco
        - DOCKER_INFLUXDB_INIT_ORG=cisco
        - DOCKER_INFLUXDB_INIT_BUCKET=css
        - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=P4By5dsQDzgqtZAGrGSUZrrJo22ALYM3-SkdlWYPji8aJK2DtW9o0vXP1N5cEq69TPL8mKPxr4mxxYfJdSFKNA== 
        - INFLUXDB_HTTP_AUTH_ENABLED
      ports:
        - '8086:8086'
      volumes:
        - influxdb-data:/var/lib/influxdb2
        - influxdb-data:/etc/influxdb2 
    grafana:
      build:
        context: ./
      container_name: grafana_css
      ports:
        - 3000:3000
      depends_on:
        - influxdb
      links:
        - influxdb        
      volumes:
        - grafana-data:/var/lib/grafana
# Explicitly define the persistent volume for your data storage
volumes:
  grafana-data:
  influxdb-data:
#    external: true