{
 "title": "Adoption Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Services Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Services",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"services\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"p1\" or r[\"_field\"] == \"p2\" or r[\"_field\"] == \"p3\" or r[\"_field\"] == \"p4\" or r[\"_field\"] == \"p5\")\r\n  |> group(columns: [\"_measurement\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Services Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"services\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"p1\" or r[\"_field\"] == \"p2\" or r[\"_field\"] == \"p3\" or r[\"_field\"] == \"p4\" or r[\"_field\"] == \"p5\")\r\n  |> group(columns: [\"service\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Priority Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"services\")\r\n  |> filter(fn: (r) =>  r[\"_field\"] == \"p1\" or r[\"_field\"] == \"p2\" or r[\"_field\"] == \"p3\" or r[\"_field\"] == \"p4\" or r[\"_field\"] == \"p5\")\r\n  |> group(columns: [\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "P1 Services Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "  from(bucket: \"css\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"services\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"p1\" )\r\n  |> group(columns: [\"_measurement\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n  "
    }
   ]
  },
  {
   "title": "P1 Services Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"services\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"p1\")\r\n  |> group(columns: [\"service\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "P2 Services Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"services\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"p2\")\r\n  |> group(columns: [\"service\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "P5 Services Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"services\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"p5\")\r\n  |> group(columns: [\"service\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Devices by priority", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "P1 Devices Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"priorities\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"p1\")\r\n  |> group(columns: [\"ned\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "P2 Devices Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"priorities\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"p2\")\r\n  |> group(columns: [\"ned\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "P3 Devices Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"priorities\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"p3\")\r\n  |> group(columns: [\"ned\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "P4 Devices Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"priorities\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"p4\")\r\n  |> group(columns: [\"ned\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "P5 Devices Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"priorities\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"p5\")\r\n  |> group(columns: [\"ned\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "IOS-XR Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"priorities\")\r\n  |> filter(fn: (r) => r[\"ned\"] == \"cisco-iosxr-cli-7.33\")\r\n  |> group(columns: [\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "IOS Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"priorities\")\r\n  |> filter(fn: (r) => r[\"ned\"] == \"cisco-ios-cli-6.69\")\r\n  |> group(columns: [\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Other Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"priorities\")\r\n  |> filter(fn: (r) => r[\"ned\"] != \"cisco-ios-cli-6.69\" and r[\"ned\"] != \"cisco-iosxr-cli-7.33\")\r\n  |> group(columns: [\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Changes Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Total Changes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"changes\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"qty\")\r\n  |> group(columns: [\"_measurement\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Changes Distribution",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 15, "x": 4, "y": 35 },
   "targets": [
    {
     "query": "from(bucket: \"css\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"changes\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"qty\")\r\n  |> group(columns: [\"change\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Licenses Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Elements",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"css\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"licenses\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Licensing Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"css\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"licenses\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Data Recorded at:",
     "type": "stat",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"css\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"licenses\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    }
   ]
  }
 ]
}